### ISSUE TITLE
Additional Feature: Marshaling (serialization)

### ISSUE THREAD

**Issue by nathanhammond** [iseki0/go-yarnlock#2]
Over at [vercel/turborepo](https://github.com/vercel/turborepo) we're intending to use this library but there is additional functionality that we would need it to support. We believe that these are probably not needed for your use case since they're presently unimplemented.

Are features like this something that you would be interested in including in this library?

**Comment by iseki0** [comment]
Of course, I think serialization is not a huge work. Do you want to make a PR? (Serialization is different than deserialization. We need a more complete model.)

**Comment by nathanhammond** [comment]
Tagging in @chris-olszewski since he is the one looking into it!

(This is where we'll be using it: https://github.com/vercel/turborepo/blob/2362f6693d31223b0e12daa716c3e855b3da6f83/cli/internal/lockfile/yarn_lockfile.go)
